# Python Numpy Basics

## Table of Contents
* [Introduction](#Introduction)
* [Requirements](#Requirements) 
  * [Knowledge](#Knowledge) 
  * [Modules](#Python-Modules)
* [Exercises](#Exercises)
* [Summary and Outlook](#Summary-and-Outlook)
* [Literature](#Literature) 
* [Licenses](#Licenses)

## Introduction

In this exercise you will learn numpy operations / features, which you will need throughout nearly all data science tasks, when working with python.

## Requirements
### Knowledge

You should have a basic knowledge of:
- numpy

Suitable sources for acquiring this knowledge are:
- [numpy quickstart](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html)
- [numpy slicing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

### Python Modules

By [deep.TEACHING](https://www.deep-teaching.org/) convention, all python modules needed to run the notebook are loaded centrally at the beginning. 


In [1]:
# External Modules
import numpy as np

## Exercises

**Task:**

Generate a numpy-1D array of length 10, all elements being 0, except the 5th element which is 1

In [2]:
### Your Solution
z = np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**Task:**

Reverse the order of vector `z`: The first element becomes the last, the second becomes the second last etc.

In [3]:
z = np.arange(50)

In [4]:
### Your Solution
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**Task:**

Find the indices of all elements that are nonzero.

In [5]:
z = np.array([1,2,0,0,4,0])

In [6]:
### Your Solution
np.where(z != 0)

(array([0, 1, 4]),)

**Task:**

Generate a 10x10 array with random values and find the smallest and largest value.

In [7]:
### Your Solution
# generate array
a = np.random.rand(10, 10) * 10

# find smallest value
print(np.amin(a))

# find largest value
print(np.amax(a))

0.18300492099275312
9.744848553707032


**Task:**

Generate a vector of length 50 with random values and calculate the mean.

In [8]:
### Your Solution
a = np.random.rand(5,1)
print(a)
print(np.mean(a, axis=0))

[[0.3228469 ]
 [0.72890759]
 [0.19472771]
 [0.28691566]
 [0.02991889]]
[0.31266335]


**Task:**


Explain the following results:

In [9]:
# jede Rechnung mit nan wird zu nan
print(0 * np.nan) 
print(np.nan - np.nan)

# is : vergleicht Objekt
# == : vergleicht Wert
print(np.nan is np.nan)

# Numpy.nan orientiert sich an IEEE-743 Spezifikation.
# https://stackoverflow.com/questions/1565164/what-is-the-rationale-for-all-comparisons-returning-false-for-ieee754-nan-values
print(np.nan == np.nan)
print(np.inf < np.nan)
print(np.inf > np.nan)

print(0.3 == 3 * 0.1) # How can you fix this?
# quantization, roundoff fehler -> ceiling
# https://docs.python.org/2/library/decimal.html
#https://kfolds.com/rounding-in-python-when-arithmetic-isnt-quite-right-11a79a30390a

nan
nan
True
False
False
False
False


**Task:**

Generate an 8x8 matrix and fill it with a chess pattern like:

`
array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])
`

In [10]:
### Your Solution
a = np.zeros((8, 8))
a[::2,::2] = 1
a[1::2,1::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

**Task:**

Generate a random 5x5 matrix and normalize (scale it by a factor) it. That means, the smallest value should become 0.0, the largest 1.0


In [11]:
### Your Solution
a = np.random.random((5, 5))
a = (a - a.min())/(a.max() - a.min())
a

array([[0.63919676, 0.23936569, 0.36151427, 0.24696555, 0.54751507],
       [0.60333555, 0.72628687, 1.        , 0.73673501, 0.7199664 ],
       [0.        , 0.40152258, 0.42209494, 0.98931771, 0.81565796],
       [0.20393398, 0.23557185, 0.13325762, 0.0080473 , 0.99157568],
       [0.89051998, 0.9223086 , 0.85271151, 0.77212133, 0.85725104]])

**Task:**

From each row, subtract the maximum value of that row.

In [12]:
z = np.arange(12).reshape((3,4))
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
### Your Solution
x = []

for row in z:
    row = row - np.max(row)
    x.append(row)

x = np.array(x)
x

array([[-3, -2, -1,  0],
       [-3, -2, -1,  0],
       [-3, -2, -1,  0]])

**Task:**
    
Divide each column by the sum of that column. Then verify that each column adds up to 1.

In [14]:
z = np.arange(12).reshape((3,4))
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
### Your Solution
(z / z.sum(axis=0, keepdims=True)).sum(axis=0)

array([1., 1., 1., 1.])

**Task:**

Negate (multiply with -1) all elements between 3 and 8 in place.

In [16]:
Z = np.arange(11)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
### Your Solution
Z[4:8] = Z[4:8]*-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


**Task:**

Explain the result (output) of the following code:

In [18]:
### Your Solution
print(sum(range(5),-1)) #python sum: 0+1+2+3+4+(-1)
from numpy import * # numpy sum on axis -1
print(sum(range(5), -1)) 
del sum

9
10


**Task:**

Generate a random vector of length 100 and sort it.

In [19]:
### Your Solution

np.sort(np.random.rand(100,1), 0)

array([[0.01425879],
       [0.01552582],
       [0.01960113],
       [0.02971494],
       [0.03346639],
       [0.04088032],
       [0.04676531],
       [0.06111647],
       [0.0882349 ],
       [0.089254  ],
       [0.08996633],
       [0.11752405],
       [0.13581991],
       [0.14747795],
       [0.16640459],
       [0.1676481 ],
       [0.18680182],
       [0.20282426],
       [0.23437016],
       [0.23721173],
       [0.24622657],
       [0.27029053],
       [0.2755087 ],
       [0.27666505],
       [0.28807608],
       [0.29388461],
       [0.31632476],
       [0.31783851],
       [0.31978722],
       [0.33037792],
       [0.34175307],
       [0.36962145],
       [0.37947499],
       [0.3855955 ],
       [0.39037286],
       [0.39101469],
       [0.39927646],
       [0.40368824],
       [0.41523449],
       [0.41712677],
       [0.42101506],
       [0.42353878],
       [0.43008432],
       [0.46206906],
       [0.47361622],
       [0.48884964],
       [0.5059099 ],
       [0.544

**Task:**

Check if two arrays are equal:

    1. All elements should be exactly the same
    2. Equality within a tolerance

In [20]:
### Your Solution
A = np.random.random((3,4))
B = A.copy()
B[1,2] = A[1,2] * 1.00000000000001
print (A)

print ("no tolerance:")
print(B == A)

print ("tolerance:")
print(np.isclose(A, B))

[[0.41738897 0.60801041 0.61518799 0.39577491]
 [0.45509625 0.05398643 0.46364449 0.28894303]
 [0.53146943 0.65673956 0.5107184  0.89303627]]
no tolerance:
[[ True  True  True  True]
 [ True  True False  True]
 [ True  True  True  True]]
tolerance:
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


**Task:**

Generate (as little code as possible) the following matrix with `np.array` and save it as the variable `arr`.

\begin{bmatrix}
1 & 1 & 1 &1  &1 \\ 
1 & 2 & 1 & 1 & 1\\ 
1 & 1 & 3 & 1 & 1\\ 
1 &1  & 1 & 4 & 1
\end{bmatrix}

And calculate:
- the sum of each line
- the sum of each row

In [25]:
arr = np.ones([4,5])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
### Your Solution

for i in np.arange(1,4):
    arr[i,i] = i+1

print(arr)
print("column:") 
print(np.sum(arr, 0))
print("row:") 
print(np.sum(arr, 1).reshape(4,1))

[[1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 3. 1. 1.]
 [1. 1. 1. 4. 1.]]
column:
[4. 5. 6. 7. 4.]
row:
[[5.]
 [6.]
 [7.]
 [8.]]


**Task:**

Generate a 2x2 matrix from `arr`: It shall consist of the 4 values when taking the values of the 2nd and 4th column of arr and the even rows.

Use different methods:
(see http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)
- integer array indexes
- slices
- boolean arrays


In [23]:
### Your Solution
# interger indexing
arr1 = np.array([[1,1],
                 [1,2]])

arr2 = np.array([[1,3],
                 [2,3]])

arr3 = arr[arr1,arr2]
print(arr3)

# slices
arr1 = arr[[1,2],1::2]
print(arr1)

# für boolean nicht geeignet, macht keinen Sinn numerische Anforderungen
# durch boolsche Abfragen anzufordern

[[2. 1.]
 [1. 1.]]
[[2. 1.]
 [1. 1.]]


**Task:**

(see http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html)

Explain the following operations on `arr`

In [30]:
print(arr)
print('--------1-------')
print(arr * 5.) # multipliziert jeden Wert mit Skalar
print('--------2-------')
print(arr.shape[1])
print(np.arange(arr.shape[1])) # Spaltenanzahl (Dimension = 1) von arr indiziert
print(arr * np.arange(arr.shape[1])) # die Werte jeder Spalte werden mit den zuvor erstellten Indizes multipliziert
print('--------3------')
print(arr.shape[0])
print(arr.T)
print(arr.T * np.arange(arr.shape[0])) # auch hier Spaltenanzahl gleich 
print('--------4-------')
print(arr * np.arange(arr.shape[0])) # Spaltenanzahl verschieden, kein Broadcasting möglich

[[1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 3. 1. 1.]
 [1. 1. 1. 4. 1.]]
--------1-------
[[ 5.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 15.  5.  5.]
 [ 5.  5.  5. 20.  5.]]
--------2-------
5
[0 1 2 3 4]
[[ 0.  1.  2.  3.  4.]
 [ 0.  2.  2.  3.  4.]
 [ 0.  1.  6.  3.  4.]
 [ 0.  1.  2. 12.  4.]]
--------3------
4
[[1. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 3. 1.]
 [1. 1. 1. 4.]
 [1. 1. 1. 1.]]
[[ 0.  1.  2.  3.]
 [ 0.  2.  2.  3.]
 [ 0.  1.  6.  3.]
 [ 0.  1.  2. 12.]
 [ 0.  1.  2.  3.]]
--------4-------


ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

**Task:**

Calculate the matrix-vector product (dot product) of `arr` and $v$:

with:

$
v = (1,2,3,4,5)^T
$

In [45]:
### Your Solution
v = np.arange(1,6)
print(v)
print(v.shape)
print(arr)
print(arr.shape)

s = arr @ v

print(s)

[1 2 3 4 5]
(5,)
[[1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 3. 1. 1.]
 [1. 1. 1. 4. 1.]]
(4, 5)
[15. 17. 21. 27.]


## Summary and Outlook

In this notebook you've picked up many of the essential numpy operations for maths and data science tasks.

The more you use the numpy library, the more of its functionality you'll discover and its usage will grow more intuitive and familiar.

## Licenses

### Notebook License (CC-BY-SA 4.0)

*The following license applies to the complete notebook, including code cells. It does however not apply to any referenced external media (e.g., images).*

Exercise: Python Numpy Basics <br/>
by Klaus Strohmenger <br/>
is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).<br/>
Based on a work at https://gitlab.com/deep.TEACHING.


### Code License (MIT)

*The following license only applies to code cells of the notebook.*

Copyright 2019 Klaus Strohmenger

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.